### ISSUE TITLE
With `:Godbolt!` also reuse existing output buffer

### ISSUE THREAD

**Issue by sbmueller** [p00f/godbolt.nvim#18]
Hi!
Currently, when invoking `:Godbolt!`, only the assembly buffer is maintained. But if `b:godbolt_exec` is set to `true`, a new output buffer is created for every call.
I think it would be more intuitive and sensible, to also apply the "bang" for overwriting the output buffer with new output contents.

**Comment by dchinmay2** [comment]
Thanks for reporting, can you try the latest commit?

**Comment by dchinmay2** [comment]
Also let me know if you have better ideas for execution interface than `b:godbolt_exec` - I just implemented it without too much thought when someone requested it

**Comment by sbmueller** [comment]
Is there a reason the flag is outside of the config struct in lua?
```lua
require("godbolt").setup({
    languages = {
        cpp = { compiler = "g122", options = {} },
        c = { compiler = "cg122", options = {} },
        rust = { compiler = "r1650", options = {} },
        -- any_additional_filetype = { compiler = ..., options = ... },
    },
    quickfix = {
        enable = false, -- whether to populate the quickfix list in case of errors
        auto_open = false -- whether to open the quickfix list in case of errors
    },
    url = "https://godbolt.org", -- can be changed to a different godbolt instance
    execute = true
})
```

**Comment by dchinmay2** [comment]
I thought people don't always want to execute their code.

It might not even be executable all the time, like when there is no `main` in the current buffer

**Comment by sbmueller** [comment]
Lets discuss the `godbolt_exec` in a separate issue.

> Thanks for reporting, can you try the latest commit?

Unfortunately still the same behavior, opening a new buffer for each execution

**Comment by dchinmay2** [comment]
> Unfortunately still the same behavior, opening a new buffer for each execution

Oh I found the bug, it's the same buffer being opened in a new split - if you edit in one window it changes in the other one too

**Comment by dchinmay2** [comment]
Fixed

**Comment by sbmueller** [comment]
Works like a charm, thanks!
